### PR TITLE
Draft asctb parser

### PR DESCRIPTION
**Pull request by dosumis**
Not yet tested.

### CODE REVIEW

**Comment by dosumis** [comment]
Fixes #5 Fixes #2

**Comment by dosumis** [comment]
@emquardokus - Checks are failing - I think because of unrecognised content in some ID cells.  Do you have an enumerated list of comments you allow in cells? Or should we add a content checker that just emits a warning that a cell is being ignored when its content doesn't match some recognised ID pattern?

**Comment by emquardokus** [comment]
@dosumis  Probably makes most sense to do the latter  because at least for now, there are bound to be things by subject matter experts we can't control.  We ask for it to conform to standard, but what we sometimes get does not and at first pass, it could be useful to flag those to look at and fix content. "Or should we add a content checker that just emits a warning that a cell is being ignored when its content doesn't match some recognised ID pattern?"

**Comment by dosumis** [comment]
ID cell checks in place.   Want to review code changes?  Then I'll merge.

**Pull request merged**
